### PR TITLE
chapter9

### PR DESCRIPTION
**Pull request by defuneste**
updating chapter 9

### CODE REVIEW

**Review by jonthegeek — APPROVED** [review]
Thanks!

**Comment by defuneste** [comment]
I am doing chap10 now (in an other branch), it will be more commits because I moved some parts that were in the previous chapter 10 to other new chapters.

**Comment by jonthegeek** [comment]
@defuneste This one is already merged. Open a new PR when you're done with 10 and we'll sort out whether we have to do anything tricky.

**Comment by defuneste** [comment]
Yes I will submit a new PR (that is why I started on new branch). I have not review the new content (this will be introduce in next chapter) nor the old one, just copy pasted.

**Pull request merged**
